steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
  - '-f'
  - './BlazorWasmHostedApp/Server/Dockerfile'
  - '.'
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
  - '--region=${_LOCATION}'
  - '--port=80'
  - '--min-instances=0'
  - '--max-instances=1'
  - '--cpu=1'
  - '--allow-unauthenticated'
images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
